/**
 * Starter soul.md template — written on first run when no soul.md exists.
 *
 * Designed to be:
 *   - valid and parseable by the manoma parser
 *   - minimal enough not to overwhelm new users
 *   - inviting — placeholders in brackets signal "fill me in"
 */

export const STARTER_TEMPLATE = `# soul.md
> Format: soul.md v1.4
> Generated by manoma-mcp on first run. Edit me — this is your portable AI identity.

---

## /config
<!-- meta: priority=medium | stability=stable | inject=by_mode | max_tokens=200 -->

\`\`\`yaml
version: 1.4
active_mode: work
default_mode: work
\`\`\`

### mode_routing

\`\`\`yaml
work:     [identity, values, voice, skills, now, preferences, memory.decisions]
personal: [identity, values, voice, preferences]
creative: [identity, values, voice, skills, preferences]
learning: [identity, values, voice, skills, preferences, memory.lessons]
\`\`\`

---

## /identity
<!-- meta: priority=high | stability=stable | inject=always | max_tokens=250 -->

\`\`\`yaml
name: [Your name]
role: [What you do]
location: [City, country]
one_liner: [A sentence that captures who you are]
\`\`\`

---

## /values
<!-- meta: priority=high | stability=stable | inject=always | max_tokens=350 -->

### core_principles

- [Principle 1 — e.g. "Craft over velocity"]
- [Principle 2 — e.g. "Clarity over cleverness"]
- [Principle 3]

### non_negotiables

- [Something you won't compromise on]

---

## /voice
<!-- meta: priority=high | stability=stable | inject=always | max_tokens=250 -->

### personality_dials

\`\`\`yaml
directness:  70/100
warmth:      50/100
humor:       40/100
formality:   30/100
verbosity:   40/100
challenge:   60/100
\`\`\`

### how_i_want_ai_to_talk

- [Be direct — don't hedge]
- [Challenge me when something seems off]
- [Skip the preamble]

---

## /skills
<!-- meta: priority=high | stability=stable | inject=by_mode | max_tokens=800 -->

### skills.summary
<!-- meta: inject=always | max_tokens=200 -->

\`\`\`yaml
domains:
  - name: "[your main skill area]"
    level: [beginner | competent | advanced | expert]
    years: [number]
    keywords: "[comma, separated, trigger, words]"

working_knowledge:
  - skill: [things you know but aren't deep in]

building_toward:
  - skill: [things you're learning]
\`\`\`

---

## /now
<!-- meta: priority=high | stability=volatile | inject=by_mode | max_tokens=500 -->

- [What you're working on right now]
- [Current focus or priority]
- [Blockers or open questions]

*Tip: ask the AI to "update my now" and it'll rewrite this section for you.*

---

## /preferences
<!-- meta: priority=medium | stability=stable | inject=always | max_tokens=200 -->

- [How you like to be communicated with]
- [Tools and workflows you prefer]
- [Things to avoid]

---

## /memory

### /memory/decisions
<!-- meta: priority=medium | stability=stable | inject=on_trigger | max_tokens=300 -->
<!-- Triggers: decision, chose, picked, went with, trade-off -->

<!-- The AI appends timestamped decisions here as you work. Keeps the last 15. -->

### /memory/lessons
<!-- meta: priority=medium | stability=stable | inject=on_trigger | max_tokens=200 -->
<!-- Triggers: lesson, learned, realized, figured out, mistake -->

<!-- The AI appends timestamped lessons here as you work. Keeps the last 15. -->

---

## /modes
<!-- meta: priority=medium | stability=stable | inject=by_mode | max_tokens=200 -->

### mode: work
[What work mode means for you — focus, projects, energy]

### mode: personal
[What personal mode means for you — off-work, relationships, hobbies]

### mode: creative
[What creative mode means for you — making, writing, building]

### mode: learning
[What learning mode means for you — reading, studying, exploring]
`;

/**
 * Welcome message prepended to the FIRST tool response after a bootstrap.
 *
 * This is the user-facing onboarding copy. It goes through the LLM so the
 * user sees it conversationally instead of buried in stderr logs.
 */
export function welcomeMessage(path: string): string {
  return `> **👋 Welcome to manoma!**
>
> I just created a starter soul.md for you at \`${path}\`. Open it in your editor and fill in the placeholders — start with \`/identity\` and \`/values\`, then flesh out the rest as it feels useful.
>
> You can also ask me to help: *"fill in my soul.md"*, *"update my /now"*, or *"add a decision: I chose X because Y"*.
>
> Docs: https://manoma.ai · Spec: https://github.com/paperdavid/manoma

---

`;
}
